### ISSUE TITLE
Include TNAST application version number as part of export metadata.

### ISSUE THREAD

**Issue by ed-g** [pouyalireza/TNAST_MAVEN#15]
I believe that the application version # is part of export meta-data, which is good, if not already in place, add application version # to some easier to access UI location.

As mentioned by Matthew this is already being done - _Where is the easy to access location of version?_

**Comment by BenFields724** [comment]
I believe this task was addressing the fact that the version number was not easily accessibly within the actual application. We added the application version number into the standard UI to fix this. Commit number108d9daa8eba56cd01d78430d799bdaf706b5314

**Comment by ODOT-RPTD-mb** [comment]
version # at bottom of agency drip down list.
