### ISSUE TITLE
Where is the application version # in the export metadata?

### ISSUE THREAD

**Issue by antrim** [pouyalireza/TNAST_MAVEN#18]
I believe that the application version # is part of export meta-data, which is good, if not already in place, add application version # to some easier to access UI location.

As mentioned by Matthew this is already being done  - _Where is the easy to access location of version?_

**Comment by ed-g** [comment]
Duplicate for #15

**Comment by ed-g** [comment]
We can close this ticket when we have github contributor status to do so.
