### ISSUE TITLE
May I be added as a contributer to this repository?

### ISSUE THREAD

**Issue by ed-g** [pouyalireza/TNAST_MAVEN#2]

**Comment by antrim** [comment]
Can I also be added as a contributor to this repo?
@srinivas13794 @pouyalireza

**Comment by pouyalireza** [comment]
You have been added let us know if it works or you have any other issues

**Comment by ed-g** [comment]
I have access. Thank you!

**Comment by ed-g** [comment]
Can we also add @PPaulsonOregonDOT as collaborator

**Comment by pouyalireza** [comment]
Philip has also been added.Please let us know if it works.

**Comment by ed-g** [comment]
@pouyalireza looks great thank you!

May I request one more, to add @antrim as collaborator.

**Comment by ed-g** [comment]
Also, if David.Porter@oregonstate.edu, venkates@oregonstate.edu, or fieldsbe@oregonstate.edu will be working on this project, can you add their github users as collaborators as well? That way we can assign tasks to them.

**Comment by ed-g** [comment]
@pouyalireza can you please add these contributors?

**Comment by pouyalireza** [comment]
@srinivas13794  @BenFields724  have been added as contributors.

**Comment by ed-g** [comment]
@pouyalireza thank you!

Would you please add @antrim as a contributor?

**Comment by ed-g** [comment]
@pouyalireza can you also please add David Porter?

I'm wanting to at-mention him on a ticket.

**Comment by ed-g** [comment]
Ping. Can you please add David Porter.

**Comment by pouyalireza** [comment]
@ed-g  I have already sent an invite out to @antrim  please let me know if I need to resend it.

**Comment by ed-g** [comment]
@pouyalireza ok great :-)

Does David Porter have a github user?

Thanks for taking care of all this. Ahh the joys of project management.

**Comment by antrim** [comment]
I received and accepted the collaborator invitation.
"You now have push access to the pouyalireza/TNAST_MAVEN repository."
