### ISSUE TITLE
META: organize issues into low-hanging versus more complicated features.

### ISSUE THREAD

**Issue by ed-g** [pouyalireza/TNAST_MAVEN#25]

**Comment by ed-g** [comment]
Perhaps categorize into two milestones.

**Comment by ed-g** [comment]
Or, two labels.

**Comment by ed-g** [comment]
Hi @PPaulsonOregonDOT @pouyalireza would you please go through the tickets for this project and categorize each one as either "easy" or "hard" using the Github labels feature?

I've created those labels to this project. Easy refers to low hanging fruit from our conversation the other day, and hard to the more complicated features.

**Comment by ed-g** [comment]
@PPaulsonOregonDOT @pouyalireza @pbarahimi @mohsenis would one of you please categorize the tickets as "easy" or "hard" so that we can make a work plan?

**Comment by ed-g** [comment]
@srinivas13794 @BenFields724 @pouyalireza @PPaulsonOregonDOT can you decide among yourselves in the next day and nominate someone to classify tasks as easy or hard?

Don't agonize over it, we can re-classify later. This is just a first step.

@antrim

**Comment by ed-g** [comment]
Labels are available in the right hand side of any individual ticket, or in the tickets list view, select tickets with a check box then the header will allow you to apply lablels.

**Comment by ed-g** [comment]
https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/

**Comment by ed-g** [comment]
@pouyalireza @srinivas13794 @BenFields724

Phil has started on this work. Can you divide/delegate among yourselves a review for every untagged issue. Or -- if the person assigned to evaluate the difficulty of an issue can't decide if its "easy" or "hard", they can categorize as "difficulty unknown" and include a comment with a reason why the issue cannot be categorized.

Can you commit to getting this done this week, before Friday 25 August?

> I've labelled all of the tasks that I feel remotely qualified to provide input on. I can take a guess at some of the others, but I will likely be off the mark.
> Phil
>

**Comment by BenFields724** [comment]
Yes. We can most definitely get that squared away in the next couple days if not tomorrow.

**Comment by BenFields724** [comment]
The tasks have been categorized. Feel free to update or change.

**Comment by ed-g** [comment]
Hi @BenFields724 

I don't mean to be a lawyer but can you include a comment with a reason why the issue cannot be categorized, for the two tickets which you classified as "difficulty unknown".

The end goal here is to have a list of next steps for each task. If we don't know enough even to classify it as easy or hard the reasoning why not at least gives me a starting point to investigate the task, as someone who is not yet familiar with the code.

Thank you!

Ed

**Comment by pouyalireza** [comment]
@ed-g  I have made comments to both the tasks labelled difficulty unknown.We would need more information on both these tasks.Please read through my comments and the task descriptions and let me know if you have any questions.

Thanks.

**Comment by ed-g** [comment]
@pouyalireza perfect, thank you!!!
