### ISSUE TITLE
Aggregated Urban Area Report

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [pouyalireza/TNAST_MAVEN#30]
http://tnasoftwaretool.engr.oregonstate.edu:8080/TNAtoolAPI-Webapp/GeoUAreasRReport.html?&popMin=0&popMax=2000000&dbindex=8&popYear=2010

Not completing in 40+ minutes, outside of ODOT environmen6 with default values.

**Comment by ed-g** [comment]
@pouyalireza @BenFields724 @tnatool 

Can you produce a log file for this operation?

What tools do we have to gather information necessary to debug this problem?

**Comment by pouyalireza** [comment]
As far as debugging goes we usually look at the console on the browser and eclipse.I am not too familiar with a log file could you please let me know what such a file would specifically contain. Right now we have narrowed down the error to be a problem with a hibernate mapping file and we are working on fixing it.

**Comment by pouyalireza** [comment]
@ODOT-RPTD-mb  this bug has been fixed.The report should load now.Please let me know if it works.

Thanks.

**Comment by ODOT-RPTD-mb** [comment]
It is working for me, outside of ODOT environment.
