### ISSUE TITLE
Data in Statewide Report

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [pouyalireza/TNAST_MAVEN#31]
Under the statewide report, the tool is currently reporting that there are 36 ODOT Transit Regions, but there are only 6. When you click the hyperlink, the report you reach only has 6 regions listed.

**Comment by pouyalireza** [comment]
@PPaulsonOregonDOT  This error has been fixed in commit  2ab8458097531ed835e6e0cb2e6e083b35448e31
