### ISSUE TITLE
New install: TNAtoolAPI-Webapp has broken links to some scripts.

### ISSUE THREAD

**Issue by ed-g** [pouyalireza/TNAST_MAVEN#33]
These urls are not loading on my install of TNAST:

The following may be because I installed my WAR file directly after compiling "mvn package" so that it has the name `TNAtoolAPI-Webapp-0.0.1-SNAPSHOT.war` and my url with tomcat is http://127.0.0.1:8080/TNAtoolAPI-Webapp-0.0.1-SNAPSHOT

http://127.0.0.1:8080/TNAtoolAPI-Webapp/queries/transit/menu?day=null&dbindex=-1&username=admin
http://127.0.0.1:8080/TNAtoolAPI-Webapp/FileUpload?getSessionUser=gsu
http://127.0.0.1:8080/TNAtoolAPI-Webapp/queries/transit/DBList
http://127.0.0.1:8080/TNAtoolAPI-Webapp/modifiers/dbupdate/getVersion
http://127.0.0.1:8080/TNAtoolAPI-Webapp/modifiers/dbupdate/getDefaultDbIndex
In other words either:

* the install intructions need to include how to build proper names with Tomcat,
* or the URLs should be changed not to require a specific installation path.

These following urls appear to be simply broken regardless of the install path. I think there is an extra '../' in the URL.

http://127.0.0.1:8080/resources/images/287.GIF
http://127.0.0.1:8080/resources/data/navigation-tree.js?_=1504207027398
http://127.0.0.1:8080/resources/images/287.GIF

Based on a quick inspection of the source:
```
$ ag 287.GIF 
src/main/webapp/TNAtoolAPI-Webapp/Emp.html
130:		<div id="dialogPreLoader"><img src="../resources/images/287.GIF" alt="Page Loading" style="width:90px; height:90px; position: absolute; margin: auto; top: 0; left: 0; right: 0; bottom: 0;" >

src/main/webapp/TNAtoolAPI-Webapp/ShapeFileExport.html
83:    		bottom:0;" alt="Loading..." src="../resources/images/287.GIF"><br>

src/main/webapp/TNAtoolAPI-Webapp/HeatMap.html
397:				id="dialogPreLoader" src="../resources/images/287.GIF"

src/main/webapp/TNAtoolAPI-Webapp/T6.html
281:		<img id="dialogPreLoader" src="../resources/images/287.GIF" alt="Page Loading" style="width:100px; height:100px; position: absolute; margin: auto; top: 0; left: 0; right: 0; bottom: 0;" >

src/main/webapp/TNAtoolAPI-Webapp/index.jsp
79:		<img id="dialogPreLoader2" src="../resources/images/287.GIF" alt="Page Loading" width="85" height="85" style="margin:100px" >
339:      <img id="dialogPreLoader" src="../resources/images/287.GIF" alt="Page Loading" style="margin:9em;margin-top:22em" >     

src/main/webapp/resources/js/ConnectivityGraph0.js
22:	var loaderHtml = '<img id="conGraphPreLoader" src="../resources/images/287.GIF" alt="Page Loading" style="height:80; width:80; margin:120px" >';

```

**Comment by ed-g** [comment]
Hmm, I've re-installed to http://127.0.0.1:8080/TNAtoolAPI-Webapp/ but some of these links are still broken:

http://127.0.0.1:8080/TNAtoolAPI-Webapp/modifiers/dbupdate/getVersion
http://127.0.0.1:8080/TNAtoolAPI-Webapp/queries/transit/DBList
http://127.0.0.1:8080/TNAtoolAPI-Webapp/FileUpload?getSessionUser=gsu
http://127.0.0.1:8080/TNAtoolAPI-Webapp/queries/transit/menu?day=null&dbindex=-1&username=admin

**Comment by ed-g** [comment]
Upshot is the menu bar keeps "loading" indefinitely.

![transit network analysis tool](https://user-images.githubusercontent.com/2495118/29941976-21be02da-8e49-11e7-8f6f-6fe54e7567df.png)

**Comment by ed-g** [comment]
There is a file which should be installed to:

./src/main/resources/com/model/database/connections/transit/mapping/GtfsMapping.hibernate.xml

**Comment by ed-g** [comment]
@BenFields724 the GtfsMapping.hibernate.xml file which you emailed me looks to be the same as the file currently in the source code.

https://github.com/pouyalireza/TNAST_MAVEN/blob/master/TNAtoolAPI-Webapp/src/main/resources/com/model/database/connections/transit/mapping/GtfsMapping.hibernate.xml

Should this file require some edits?

**Comment by BenFields724** [comment]
[NewInstanceFiles.zip](https://github.com/pouyalireza/TNAST_MAVEN/files/1268462/NewInstanceFiles.zip)

**Comment by BenFields724** [comment]
It was provided by Pouya when I was setting up my instance so it may have been a redundant replacement. Not sure if there was anything actually changed for that file.  My familiarity with hibernate mapping is minimal so I can't really speak to that at the moment.

**Comment by BenFields724** [comment]
@ed-g @ODOT-RPTD-mb @pouyalireza I have attached a word file that covers the steps to resolve problems with a new instance. 
[installDocument.docx](https://github.com/pouyalireza/TNAST_MAVEN/files/1282421/installDocument.docx)

**Comment by ed-g** [comment]
Text from word file.

> 
> Note: When building in the eclipse environment we are using run-as maven build with a goal of ‘tomcat7:run’
> 
> After initial Git clone into eclipse there is one build path error encountered:
> Project 'TNAtoolAPI-Webapp' is missing required source folder: 'src/test/resources 
> 
> To resolve, configure build path and remove the missing sources 'src/test/resources’ and 'src/test/java’
> 
> The application will load but the menu bar never finishes loading from what appears to be a hibernate mapping problem according to the eclipse console. Not positive what the cause is, but I believe it is a mapping problem between the database info files and the organization of the databases within the project. 
> 
> To resolve, remove all databases located in ‘src/main/resources/com/model/database/connections/spatial’ 
> ‘src/main/resources/com/model/database/connections/transit’
> 
> Then place the provided database for march-2017 into the same locations.
> 
> Open dbinfo.cvs located in ‘src/main/resources/admin’ and remove all mappings except for the mar-17 database and change index to 0. 
> 
> The application should load correctly after this. 
> 
> Add additional databases in a similar fashion making sure the mappings are correct. 
> 
> 
> 
> 
> 
>

**Comment by ed-g** [comment]
Contents from NewInstanceFiles.zip, renamed to .txt to meet with githubs file name restrictions:

[march17.cfg.xml.txt](https://github.com/pouyalireza/TNAST_MAVEN/files/1285574/march17.cfg.xml.txt)
[mapping.hbm.xml.txt](https://github.com/pouyalireza/TNAST_MAVEN/files/1285576/mapping.hbm.xml.txt)
[GtfsMapping.hibernate.xml.txt](https://github.com/pouyalireza/TNAST_MAVEN/files/1285577/GtfsMapping.hibernate.xml.txt)
[dbInfo.csv.txt](https://github.com/pouyalireza/TNAST_MAVEN/files/1285575/dbInfo.csv.txt)

**Comment by ed-g** [comment]
I edited the various database configurations to refer to my local database server. And changed database user to tnast (regular user) instead of postgres (superuser).

**Comment by ed-g** [comment]
DBlist is returning 404. How can we get a log file for this?

http://127.0.0.1:8080/TNAtoolAPI-Webapp/queries/transit/DBList

> HTTP Status 404 - /TNAtoolAPI-Webapp/queries/transit/DBList
> 
> type Status report
> 
> message /TNAtoolAPI-Webapp/queries/transit/DBList
> 
> description The requested resource is not available.
> Apache Tomcat/8.0.32 (Ubuntu)

**Comment by ed-g** [comment]
Hi did you folks get my message earlier? I need a current copy of the postgresql dump files. Ones in google docs are all more than a year old.

https://github.com/pouyalireza/TNAST_MAVEN/issues/6#issuecomment-327870334

**Comment by srinivas13794** [comment]
Ed,
I will upload them onto the drive as soon as they are ready.

Thanks

**Comment by srinivas13794** [comment]
@ed-g an invite for a box folder containing all the backups for all databases has been sent to you.Please let me know if you did received it.

**Comment by ed-g** [comment]
@srinivas13794 thank you! I have received the files.

**Comment by ed-g** [comment]
Closing, all but one of these links are working now. 

http://127.0.0.1:8080/TNAtoolAPI-Webapp/queries/transit/menu?day=null&dbindex=-1&username=admin

And we have a separate ticket #54 open for that one.
