### ISSUE TITLE
Key Transit Hubs Summary Report

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [pouyalireza/TNAST_MAVEN#34]
For 1 May 2017 & default values Portland key transit hub with 20k+ visits, Expanded stop view, Visit counts for Portland Streetcar stops show up as "undefined".

**Comment by PPaulsonOregonDOT** [comment]
In the same report, I checked the Eugene to Coos Bay and Eugene to Bend agencies, both of which expired prior to 5/1/17, and this report show reasonable results for this report for those agencies. This suggest that this is not related to expired feeds, and that this report should be built in such a way that expired feeds do not show visits for dates for which their feeds are expired, which appears to be a consistent trend in other reports.

**Comment by srinivas13794** [comment]
@ed-g Reason for undefined visit count is that the agencyid is used to fetch visit counts instead of the defaultid and the reason for the visit count to show even after expiry is that the visit count order is changed i.e. the association of visit count to stopid are not right.

**Comment by ed-g** [comment]
I loaded the key transit hubs report but I don't see a way to expand to Portland or a stops view. I think I'm looking in the wrong place.

http://tna.trilliumtransit.com/TNAtoolAPI-Webapp/KeyHubSreport.html?&x1=0.08&x2=0.25&x3=2.0&n=ior&dbindex=9&popYear=2010

What is the URL for this report?

**Comment by pouyalireza** [comment]
@ed-g  the URL you have sent is correct.If you scroll to the right you should see a column called stops 
![image](https://user-images.githubusercontent.com/12384084/30504091-b73ff24e-9a21-11e7-960a-7ce79bd27f6c.png)
If you expand this column you should see stop details
![image](https://user-images.githubusercontent.com/12384084/30504170-1d65e61e-9a22-11e7-8159-3bfaf3ad5791.png)

**Comment by ed-g** [comment]
Oh I see. One issue for my browser is there is no horizontal scroll bar shown.

**Comment by srinivas13794** [comment]
You have to scroll down to the end of the table just before where you can
select different pages.

**Comment by ed-g** [comment]
Ok thanks!

**Comment by ed-g** [comment]
@srinivas13794 

I'm not as familiar with the database as you are so my question might not make sense.

Is this an issue with the way the database is organized, in that maybe I could help to write a query to find the relationship?

Or is the relationship available but the tna software doesn't use it.

I don't really know enough to be helpful yet so let me know if there is something I can do, or as I learn more I might try a fix.

> Reason for undefined visit count is that the agencyid is used to fetch visit counts instead of the defaultid and the reason for the visit count to show even after expiry is that the visit count order is changed i.e. the association of visit count to stopid are not right.

**Comment by srinivas13794** [comment]
@ed-g @BenFields724  I think it would be  a good idea to set up a call to discuss this and the other tasks so we can be on the same page.Please let me know what times work for you.

**Comment by ed-g** [comment]
I'm available today or on Friday.

**Comment by srinivas13794** [comment]
@ed-g  @BenFields724 What time would work for you today ?

**Comment by ed-g** [comment]
Any time today. I need to keep it to a half hour though.

**Comment by srinivas13794** [comment]
@ed-g 12:00 pm works for both me and ben. Does that work ?

**Comment by ed-g** [comment]
Yes I can call you at the same number?

**Comment by srinivas13794** [comment]
@ed-g  Yes that works.Thanks a lot.

**Comment by ed-g** [comment]
> There's no problem with database itself. It's with how its quoted in java, gives a few errors.

**Comment by ed-g** [comment]
Each agency has an agency_id and an default_id. This can cause problems.

```sql
may17=# select array_agg(id), defaultid from gtfs_agencies group by defaultid having count(*) > 1;
-[ RECORD 1 ]----------------
array_agg | {131,215}
defaultid | 131
-[ RECORD 2 ]----------------
array_agg | {86,188}
defaultid | 86
-[ RECORD 3 ]----------------
array_agg | {94,225}
defaultid | 94
-[ RECORD 4 ]----------------
array_agg | {157,159}
defaultid | 157
-[ RECORD 5 ]----------------
array_agg | {22,253,57}
defaultid | 22
-[ RECORD 6 ]----------------
array_agg | {456,457}
defaultid | 456
-[ RECORD 7 ]----------------
array_agg | {37,531}
defaultid | 37
-[ RECORD 8 ]----------------
array_agg | {TRIMET,PSC,TRAM}
defaultid | TRIMET
```

**Comment by PPaulsonOregonDOT** [comment]
This issue appears to be resolved for Portland Streetcar,, but in the same drop down menu in that report, now the Columbia Area Transit stop is showing an undefined visit count.

**Comment by ed-g** [comment]
@BenFields724 @srinivas13794 any update on this?

**Comment by ed-g** [comment]
Thanks for the update! Is there any way I can help?

**Comment by ed-g** [comment]
@srinivas13794 can you give me whatever rough draft of any fix, or documentation of what you see as the underlying problem.

**Comment by ed-g** [comment]
Threading implementation was a problem to fix.

**Comment by ed-g** [comment]
OK if the code doesn't work or if it has bugs -- just a place for me to start from.

**Comment by ed-g** [comment]
@srinivas13794 please post the any code you have, so I don' t need to start implementation from scratch. I don't care if it runs or not or looks good. Just send me what you have.

**Comment by srinivas13794** [comment]
@ed-g I apologize for the delay.Attached is a document with recommended fixes to the problems in this report.
[Key_Transit_hubs.docx](https://github.com/pouyalireza/TNAST_MAVEN/files/1389338/Key_Transit_hubs.docx)

**Comment by ed-g** [comment]
@srinivas13794 thank you!! :-)
