### ISSUE TITLE
Connection to server for file transfer

### ISSUE THREAD

**Issue by BenFields724** [pouyalireza/TNAST_MAVEN#35]
When trying to connect to the server I get a response that no more users can connect. I am using the ftps protocol provided by mac. 
![image](https://user-images.githubusercontent.com/21002354/30184107-ac77ef2a-93d1-11e7-8147-ef3e443f88c8.png)

**Comment by ed-g** [comment]
@BenFields724 file transfer has an array confusingly similar but distinct and incompatible protocols.

See if your client supports "SFTP" which is ssh file transfer.

Or use filezilla which I know does support SFTP.

https://filezilla-project.org/

**Comment by ed-g** [comment]
Post a picture of the configuration dialog box if you still run into trouble.

**Comment by BenFields724** [comment]
Yeah I tried filezilla as well which was failing to connect. 

![image](https://user-images.githubusercontent.com/21002354/30184390-cb43f1e6-93d2-11e7-8dd7-ea7106cd8c26.png)

**Comment by ed-g** [comment]
@BenFields724 filezilla is configured to use FTP (you can see port 21).

Can you configure to use SFTP (port 22, ssh-based) you'll likely need to tell it where to find your ssh key, it's typically under $HOME/.ssh/

**Comment by ed-g** [comment]
https://en.wikipedia.org/wiki/Category:SFTP_clients

https://en.wikipedia.org/wiki/Comparison_of_SSH_clients

**Comment by ed-g** [comment]
Another option for mac is Transmit

https://en.wikipedia.org/wiki/Transmit_(FTP_client)

**Comment by ed-g** [comment]
@BenFields724 just confirming you were able to connect. Which client did you end up using, would you be able to help @srinivas13794 connect using the same client?

**Comment by ed-g** [comment]
FYI in case you were testing file transfer. I'm restarting the server for an upgrade and it should be available again at 3:30pm today.

**Comment by ed-g** [comment]
The tna.trilliumtransit.com server is available again.

**Comment by ed-g** [comment]
A few notes copied from email. For connection from Windows machine.

> Then see if you can transfer files using WinSCP (or any other SFTP client). You can use SFTP or SCP protocol.
> 
> https://winscp.net/eng/index.php
> 
> You may need to "import" your ssh key based on docs I found here. Or it might work without an "import" step.
> 
> https://winscp.net/eng/docs/ui_puttygen "Dealing with Private Keys in Other Formats"
>

**Comment by BenFields724** [comment]
@ed-g  Regarding your comment for the confirmation of connecting to the server, yes I was able to connect through ssh and then through filezilla as well. We tried to get Srinivas' machine setup, but the connection was failing. On first thought it might be a public key format problem, but I am not sure.

**Comment by ed-g** [comment]
Ok thanks for your work on this.

For PuTTY have you tried the instrctions I linked to above?

It looks like filezilla has an SSH key import function. https://wiki.filezilla-project.org/Howto

Please post screenshots of your configuration dialog and error messages!

**Comment by ed-g** [comment]
WinSCP might be easier to set up than Filezilla on windows -- if one doesn't work after 10 minutes of configuration I'd recommend trying the other. Putty claims to have a built-in file transfer function but I've never used it.

**Comment by ed-g** [comment]
Mentioned this to Srinivas. You might try asking for help from OSU's IT department. They should be knowledgeable about how to set up SSH and SFTP clients.

**Comment by ed-g** [comment]
@BenFields724 can you get access to a windows machine and experiment with configuring PuTTY and either WINSCP or FileZilla? When you generate a new key you can send it to me and I'll add authorization for it for tnatool@tna.trilliumtransit.com.

Since it sounds like Srinivas has a final today and we need to have access up and running for both of you before Monday morning.

**Comment by BenFields724** [comment]
@ed-g 
here is a key for my windows machine
ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAvfNyT6PYkM71gepHpIPK452QuPceqGzMnnOJ9kmAmgF4Wm+IJKqsYkGhAzPdaHR7xIpCVc3YXalzYZ+7fhR6Ovs5Iw8z7TIgiRIa8jLFkQXEwiSrgoy4IALEZa4Jqp/7zWtFif/lJhSFLsYtFeIsEAKgVN2eBEolD0Gx/crfQDOsh5T+osWHAVjV1bCESXVOSf1kMkKVjse69eJa+picVxLffrYPJ9XGvFoBT1yzhSCqkf1CkCj5Pn8BJX9B8sVhZgdhSY/5sKSO39OyZLGhmYLOP5g6OUCNtUcCSWljmixqGBMYWjUyDsBb17ulmI4TfGvzZdeB4qhNo9OCoDZoMw== rsa-key-20170908

**Comment by ed-g** [comment]
Thanks @BenFields724 

I've installed on to server. Would you see if you can login using PuTTY and tranfer files using either WINSCP or FileZilla.

**Comment by BenFields724** [comment]
@ed-g  I can connect with FileZilla but Putty is failing to connect. It just says access denied.

**Comment by ed-g** [comment]
screen shots please

**Comment by BenFields724** [comment]
![image](https://user-images.githubusercontent.com/21002354/30229774-1d24ffa8-9498-11e7-9efd-9346ab06b685.png)
![image](https://user-images.githubusercontent.com/21002354/30229794-2de7f7c8-9498-11e7-9dce-c487e8d2592d.png)

**Comment by ed-g** [comment]
did you configure the putty rsa key login?

See if these howtos help.

https://www.howtoforge.com/how-to-configure-ssh-keys-authentication-with-putty-and-linux-server-in-5-quick-steps

https://www.ibm.com/developerworks/community/blogs/Dougclectica/entry/ssh_key_authentication_with_putty30?lang=en

**Comment by ed-g** [comment]
https://www.electrictoolbox.com/putty-rsa-dsa-keys/

**Comment by BenFields724** [comment]
@ed-g  Success. Had the key in the wrong location. Should have it figured out for SFTP and SSH connections and can get Srinivas' machine setup.

**Comment by ed-g** [comment]
Great. Thanks for your help with this.
