### ISSUE TITLE
Docs for eclipse

### ISSUE THREAD

**Issue by ed-g** [pouyalireza/TNAST_MAVEN#36]
Hi All,

I have been installing based on the documentation here: https://github.com/pouyalireza/TNAST_MAVEN/blob/master/README.md

Is there more documentation available which includes specific instructions for eclipse?

I have generally never had a problem installing a maven-based java project using maven and tomcat directly -- but I'd be happy to give eclipse a shot if that makes things easier.

Ed

**Comment by BenFields724** [comment]
@ed-g Our workflow has been through the Eclipse IDE with the web tools package and Git tools installed. So once Eclipse is installed we clone the git repo using the git repository tools and select import projects. I am a bit unfamiliar with the earlier stages of the project and whether or not the repo contains configuration files unique to eclipse which could potentially cause problems outside of eclipse. It would likely be cleaner to have the tool running independently from Eclipse, but I don't know that the tool has ever been set up in such a way.

**Comment by ed-g** [comment]
Ok Ben thanks for the background!

It sounds to me like the eclipse IDE does the same steps behind the scenes as I'm doing using the command line:

* `git pull` to grab the source code.
*  `mvn package` to build a war (web application archive) file.
* Install the war file to the web server under the name TNAtoolAPI-Webapp.

As far as I can tell I'm not running into any errors with the deployment process. What's happening is the tool is installing and then not doing anything.

That being said I'll give eclipse build a shot and see if it does anything differently.

**Comment by ed-g** [comment]
Closing, Eclipse doesn't do anything for running the server that Tomcat doesn't do.
