### ISSUE TITLE
Server URL issue :

### ISSUE THREAD

**Issue by pouyalireza** [pouyalireza/TNAST_MAVEN#37]
http://tnasoftwaretool.engr.oregonstate.edu:8080/?&n=--&dbindex=8
The trillium server has an extra  TNATool-Webapp.
http://tna.trilliumtransit.com:8080/TNATool-Webapp/?&n=--&dbindex=0

**Comment by ed-g** [comment]
thanks for filing. can you please include a url from the osu server, and one from trillium server to show how they differ?

**Comment by ed-g** [comment]
I've updated the INSTALL.sh file to install to the ROOT.war file on tomcat. This might match your configuration at OSU.

**Comment by ed-g** [comment]
@pouyalireza good work spotting this. You saved me many hours of debugging.
