### ISSUE TITLE
windows specific code in DbUpdate.java?

### ISSUE THREAD

**Issue by ed-g** [pouyalireza/TNAST_MAVEN#42]
https://github.com/pouyalireza/TNAST_MAVEN/blob/4208e43aa7c8dd1df489ebceb744b29fc07977e9/TNAtoolAPI-Webapp/src/main/java/com/webapp/modifiers/DbUpdate.java#L101

This windows specific code need to be rewritten.

**Comment by ed-g** [comment]
This code pre-dates Srinivas, Ben's involvement in the project.

**Comment by ed-g** [comment]
From looking at this file more, it appears that while these paths are defined, they might only be referenced in code which is commented out.

```java
	private final static String basePath = "C:/Users/tnatool/Development/Repository/test/";
        private final static String psqlPath = "C:/Program Files/PostgreSQL/9.4/bin/";
```

**Comment by ed-g** [comment]
@BenFields724 @srinivas13794 would one of you please remove these windows paths? They don't appear to be used.

**Comment by BenFields724** [comment]
fixed. commit d3cb3523bb4bb04a812ad01f6bda10a36416fd4c

**Comment by ed-g** [comment]
Thanks @BenFields724

Looks good!

Would you go ahead a click the "Close Issue" button at the bottom of this page. :smile:
