### ISSUE TITLE
FileUpload 404

### ISSUE THREAD

**Issue by ed-g** [pouyalireza/TNAST_MAVEN#45]
http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/FileUpload?getSessionUser=gsu

HTTP Status 404 -

type Status report

message

description The requested resource is not available.
Apache Tomcat/7.0.69

**Comment by ed-g** [comment]
We don't understand what's going on here.

Maybe the file is in the wrong place.

**Comment by ed-g** [comment]
http://tnasoftwaretool.engr.oregonstate.edu:8080/TNAtoolAPI-Webapp/FileUpload

**Comment by ed-g** [comment]
https://github.com/pouyalireza/TNAST_MAVEN/blob/5317a6e362a857d9c8f6dae2869298f4f3fbabb4/TNAtoolAPI-Webapp/src/main/java/com/webapp/modifiers/FileUpload.java

**Comment by ed-g** [comment]
Srinivas does not think this is an error with regard to this error.

**Comment by ed-g** [comment]
There is no place you upload a file to the main map interface. What is the user name you are using. There was a playground for custom feed and choosing different feeds. Username and feeds that you selected, were uploaded to the tool. Get the username for that.

**Comment by srinivas13794** [comment]
http://tnasoftwaretool.engr.oregonstate.edu:8080/TNAtoolAPI-Webapp/FileUpload?getSessionUser=gsu

**Comment by ed-g** [comment]
Returns username: "admin".

**Comment by ed-g** [comment]
Started working. May be fixed (along with many other issues) by #51 

http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/FileUpload?getSessionUser=gsu

{"username":"admin"}
