### ISSUE TITLE
dbInf.csv (note Inf not Info), is this a duplicate?

### ISSUE THREAD

**Issue by ed-g** [pouyalireza/TNAST_MAVEN#47]
Hi @BenFields724 @srinivas13794 

While looking for db configuration, found this file:

src/main/webapp/resources/admin/dbInf.csv

https://github.com/pouyalireza/TNAST_MAVEN/blob/master/TNAtoolAPI-Webapp/src/main/webapp/resources/admin/dbInf.csv

Is this the same as dbInfo.csv? Is this file needed in this location or can we remove it?

**Comment by BenFields724** [comment]
@ed-g I noticed this as well a little while back. On my local instance I have this file as well. I deleted it and it seems to have no impact on the launching of the tool. I cannot be sure it is used for another feature of the tool though.

**Comment by ed-g** [comment]
Ok great thanks for checking, and resolving the mystery.

I'll bet it's either a "save as" typo, or intended as some kind of template for the active dbInfo.csv config file. In either case we don't need it.
