### ISSUE TITLE
add logging for java.

### ISSUE THREAD

**Issue by ed-g** [pouyalireza/TNAST_MAVEN#48]
eclipse console has a log.

**Comment by ed-g** [comment]
Please add a screen shot of eclipse console, or link to docs. I can see about enabling this on the server.

**Comment by ed-g** [comment]
You also mentioned break points. I've seen reference to eclipse debugging through tomcat -- let me know which debugger tool you're using (and the version if one is available).

**Comment by ed-g** [comment]
We may be able to add more debugging logs in the main tomcat log. No idea if this guide is still current but somewhere to start.

https://www.mulesoft.com/tcat/tomcat-logging

**Comment by pouyalireza** [comment]
![image](https://user-images.githubusercontent.com/12384084/30300135-e27dfc2a-9707-11e7-81e0-89fbd0947259.png)
This is an example of our logging in eclipse

**Comment by ed-g** [comment]
@pouyalireza thanks this is a great starting place for me. I might ask you for more details.

Am I speaking with Pouya, or Srinivas logged in as Pouya's github user?

**Comment by pouyalireza** [comment]
@ed-g  srinivas @srinivas13794 here.

**Comment by ed-g** [comment]
Note to self. Running tomcat from the command line appears to give more logging information. We should check about modifying the tomcat unit file to log stdout and stderr to a file under /var/log/tomcat -- it's strange that it's not already configured in this way. Check RHEL or Centos docs to see if other have done this so we don't reinvent the wheel.

Those files will be large, make sure they're running through some kind of logrotate.

**Comment by ed-g** [comment]
https://access.redhat.com/solutions/2324691

> In RHEL 7, the RHEL tomcat package doesn't save all stderr and stdout to catalina.out; instead, it all goes to the systemd journal and /var/log/messages. How can this be captured to a specific file instead?

**Comment by ed-g** [comment]
Looks like everything is "managed" by systemd. Tomcat logs are available via.

journalctl -u tomcat.service

However the tnatool user does not get any output when running that command.

**Comment by ed-g** [comment]
Looks like you cannot use `>>` redirection from systemd unit files.

This solution helped.

https://stackoverflow.com/questions/37585758/how-to-redirect-output-of-systemd-service-to-a-file

But here is the magic:

rsyslog.conf
```
local6.*                                                /var/log/tomcat/catalina.out
```

And custom modified version of tomcat service file in /etc/systemd/system/tomcat.service:

```systemd

# Systemd unit file for default tomcat
# 
# To create clones of this service:
# DO NOTHING, use tomcat@.service instead.

[Unit]
Description=Apache Tomcat Web Application Container
After=syslog.target network.target

[Service]
Type=simple
EnvironmentFile=/etc/tomcat/tomcat.conf
Environment="NAME="
EnvironmentFile=-/etc/sysconfig/tomcat
ExecStart=/usr/libexec/tomcat/server start
SuccessExitStatus=143
User=tomcat
Group=tomcat
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=tomcat
SyslogFacility=local6

[Install]
WantedBy=multi-user.target
```

Note SyslogFacility matches that in rsyslog.conf

**Comment by ed-g** [comment]
@BenFields724 @srinivas13794 you can now find tnatool output as /var/log/tomcat/catalina.out

Use `tail -f` to get a real time monitoring.
