### ISSUE TITLE
how is login configured on the tna tool hosted at osu?

### ISSUE THREAD

**Issue by ed-g** [pouyalireza/TNAST_MAVEN#49]
There is an admin login and password. How is this configured?

**Comment by ed-g** [comment]
Asking since I tried the same user and password on the trillium instance, and login failed.

**Comment by ed-g** [comment]
This is high priority since some url's are returning an error Trillium's server where OSU server gives "admin" user name. Lack of a login may be causing a crash.

**Comment by BenFields724** [comment]
@ed-g @srinivas13794 I believe the only login protected features are the admin interface and connections to the databases which I think you have...?

**Comment by ed-g** [comment]
@BenFields724 

Good question, as far as I know, yes those are the only features which require login.

I have logins from the **client** side.

What I'm looking for is how the admin password was set on the **server** side.

That way I can configure Trillium's tna server the same way as OSU's.

Maybe it's hard-coded in the source somewhere, or it could be an xml file, or it could be a config file on your Windows server.

Would you mind looking around to see if you can find it?

**Comment by ed-g** [comment]
The test case is

http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/admin

I've used the same login and password as for OSU, but the login does not succeed. So the question is, is that a login failure, or another kind of failure for example the database. First step is to check the server config to see if login is the same as at OSU.

**Comment by srinivas13794** [comment]
@ed-g  The password protection is only for the admin interface and does not relate errors.I think it would best to about this during tomorrow's call.
You need to add this to the tomcat-users.xml under tomcat users I will send them to you via email.

**Comment by ed-g** [comment]
Great I've added.

I really appreciate your researching this.

**Comment by ed-g** [comment]
> Ed,
> Please add these lines and substitute the *** for the password and username I gave you or you can reset as per your preference.
> 
> <role rolename="admin"/>
>   <user username="**" password="***" roles="admin"/>
> 
> Regards,
> Srinivas

**Comment by ed-g** [comment]
Admin page now loads for me and it shows list of databases.
