### ISSUE TITLE
src/main/java/com/model/database/Databases.java appears to be reading database parameters out of the source directory

### ISSUE THREAD

**Issue by ed-g** [pouyalireza/TNAST_MAVEN#51]
```java
public class Databases {
        public static HashMap<String, String[]> infoMap = getDbInfo();
        public static String path;
        public static HashMap<String, String[]> getDbInfo() {

                HashMap<String, String[]> infoMap = new HashMap<String, String[]>();
                try {
                        path = Databases.class.getProtectionDomain().getCodeSource().getLocation().getPath();
                        BufferedReader reader = new BufferedReader(new FileReader(
                                        path+"../../src/main/resources/admin/resources/dbInfo.csv"));
                        String[] keys = reader.readLine().trim().split(",");
                        ArrayList<String[]> elem = new ArrayList<String[]>();
                        String line = reader.readLine();
                        while (line != null && !line.equals("")) {
                                elem.add(line.trim().split(","));
                                line = reader.readLine();
                        }
[...]
```

Is this really what's happening?

**Comment by ed-g** [comment]
Add logging to get the file name and see.

**Comment by ed-g** [comment]
It doesn't appear there is any logging library used by TNA tool. Google uses logging but I don't know if that's connected to anything.

https://github.com/pouyalireza/TNAST_MAVEN/search?l=Java&q=log&type=&utf8=%E2%9C%93

I'm using System.err.println as does Hutil.java

https://github.com/pouyalireza/TNAST_MAVEN/blob/8eaa238e5d70e20c23558e470c882e3635587352/TNAtoolAPI-Webapp/src/main/java/com/model/database/queries/util/Hutil.java#L35

**Comment by ed-g** [comment]
It looks tna is attempting to load csv from a non-existent file.

Attempting to load dbInfo.csv from: /var/lib/tomcat/webapps/ROOT/WEB-INF/classes/com/model/database/Databases.class../../src/main/resources/admin/resources/dbInfo.csv

We'll need to correct this csv location to work on both osu's server and Trilliums.

**Comment by ed-g** [comment]
@srinivas13794 @BenFields724 

Would one of you please re-compile and redeploy OSU's copy of the tna tool and look for the log entry with

Attempting to load dbInfo.csv from

and paste the output as a comment to this issue?

**Comment by ed-g** [comment]
I can fix this on my server but I don't want to break yours at the same time.

**Comment by ed-g** [comment]
Workaround via

https://github.com/pouyalireza/TNAST_MAVEN/commit/2e7329e73500598c36c123b4e015ea3d05fbea67

**Comment by ed-g** [comment]
The strange thing is it appears that TNA tool expects to be able to modify the CSV file from the source directory, at run time. In general this will not be possible and is not a good idea in any case.

We should move this CSV file to a configurable location which the tomcat server will have access to, for example /etc/tnatool on Linux/Mac or c:/tnatool on Window

**Comment by ed-g** [comment]
Trick to finding log message was to find a break point so that other messages didn't hide it.

**Comment by srinivas13794** [comment]
Attempting to load dbInfo.csv from: /C:/Users/tnatool/git/TNAST_MAVEN_PRODUCTION/TNAtoolAPI-Webapp/target/classes/../../src/main/resources/admin/resources/dbInfo.csv

**Comment by ed-g** [comment]
Maybe we can move window configuration to `/C:/Users/tnatool/config` and linux/mac configuration to `/etc/tnatool`

**Comment by ed-g** [comment]
Configuration Directory is set by the java property `edu.oregonstate.tnatool.ConfigurationDirectory` and if that's not available we fall back to 

```java
Databases.class.getProtectionDomain().getCodeSource().getLocation().getPath() 
+ "../../src/main/resources/"
```

**Comment by ed-g** [comment]
Config directory should be readable and writeable by both tnatool and tomcat, and set-gid so that any files created will be readable by tomcat. Some files should also be group-writable so that tomcat can edit the configuration.

[root@li257-210 home]# mkdir /etc/tnatool
[root@li257-210 home]# chown tnatool:tomcat /etc/tnatool/
[root@li257-210 tnatool]# chmod 4775 /etc/tnatool
