### ISSUE TITLE
please test tna.trilliumtransit.com and see what breaks

### ISSUE THREAD

**Issue by ed-g** [pouyalireza/TNAST_MAVEN#55]
Hi All,

Would you please spend 5 minutes on: http://tna.trilliumtransit.com:8080/

To see if you can find bugs that only show up on Trillium's hosted version?

Note I'm still working on admin pages, I would expect to problems here (although I'd still like to hear about them): http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/admin

@antrim @pouyalireza @tnatool @BenFields724 @PPaulsonOregonDOT @srinivas13794 

You can either add comments to this issue, or file individual issues for any problems you encounter.

Thanks!

**Comment by PPaulsonOregonDOT** [comment]
@ed-g is two databases currently in the trillium tool vs. the quarterly updates in the OSU tool an expected difference between the tool versions?

**Comment by ed-g** [comment]
@PPaulsonOregonDOT yes there are only two databases loaded currently.

But if there is a particular database you want to test I can load it up.

**Comment by BenFields724** [comment]
Main interface loads correctly.
![image](https://user-images.githubusercontent.com/21002354/30445276-54672922-993a-11e7-906b-d4e2bd669814.png)

URL-http://tna.trilliumtransit.com:8080/?&n=--&dbindex=1

**Comment by BenFields724** [comment]
Admin interface loading correctly. Wasn't loading the other day but it might have been the wrong URL. Correct URL -http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/admin

![image](https://user-images.githubusercontent.com/21002354/30445506-0237a720-993b-11e7-978f-dfeefbbaa03a.png)

**Comment by ed-g** [comment]
Thanks @BenFields724

**Comment by ed-g** [comment]
Would someone please check a "slow" report with a stopwatch, to see how performance compares between OSU server and Trillium server? Include the URL's for both reports, and the timing information. Here's an example table you can copy and populate.

query url | time elapsed | test date and time
--- | -- | --
http://tna.... | 1:23.45 | 2017-09-14

**Comment by PPaulsonOregonDOT** [comment]
I was expecting this to be a slower report, but these were my results:
http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/stopreport.html?&agency=456&n=inr&x=0.25&dbindex=1&popYear=2010&geotype=-1&geoid=null&areaid=null&type=null&route=null&nav=stateS-agencyS&rc=-1&stime=0:00&etime=23:59
12.35 seconds  | 12.35 | 2017-09-14
http://tnasoftwaretool.engr.oregonstate.edu:8080/TNAtoolAPI-Webapp/stopreport.html?&agency=456&n=inr&x=0.25&dbindex=6&popYear=2010&geotype=-1&geoid=null&areaid=null&type=null&route=null&nav=stateS-agencyS&rc=-1&stime=0:00&etime=23:59 | 22.66 | 2017-09-14

**Comment by PPaulsonOregonDOT** [comment]
http://tnasoftwaretool.engr.oregonstate.edu:8080/TNAtoolAPI-Webapp/stopreport.html?&agency=TRIMET&n=inr&x=0.25&dbindex=6&popYear=2010&geotype=-1&geoid=null&areaid=null&type=null&route=null&nav=stateS-agencyS&rc=-1&stime=0:00&etime=23:59 | 1:23.63 | 2017/09/14

http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/stopreport.html?&agency=TRIMET&n=inr&x=0.25&dbindex=1&popYear=2010&geotype=-1&geoid=null&areaid=null&type=null&route=null&nav=stateS-agencyS&rc=-1&stime=0:00&etime=23:59
| 1:16.54 | 2017/09/14

**Comment by ed-g** [comment]
Closing since there are no crashes reported. We can open new issues if problems arise.
