### ISSUE TITLE
Two Reports Time Out?

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [pouyalireza/TNAST_MAVEN#66]
I checked both servers, and the aggregated urban area report and the route/agencies detail reports appear to time out, even outside of the ODOT environment.

When you open up the aggregated urban area report from the main report tab, it does not complete, and appears to time-out. Interestingly, this report completes just fine if you access the transit agency report and select the urban areas hyperlink.

A potentially related issue is that when you try to access agencies or routes reports from the any of the geographic base reports (counties, ODOT regions, etc), the report appears to time out.

**Comment by ed-g** [comment]
@PPaulsonOregonDOT can you link URL's and I'll use those for trial and error to improve performance.

**Comment by PPaulsonOregonDOT** [comment]
@ed-g:
Aggregated Urban Areas Report
http://tna.trilliumtransit.com/TNAtoolAPI-Webapp/GeoUAreasRReport.html?&popMin=0&popMax=2000000&dbindex=10&popYear=2010

http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/GeoUAreasRReport.html?&popMin=0&popMax=2000000&dbindex=10&popYear=2010

Agency/Route Reports:
http://tna.trilliumtransit.com/TNAtoolAPI-Webapp/GASReport.html?&areaid=41001&type=0&dbindex=10&popYear=2010&geotype=-1&geoid=null&nav=stateS-countyS

http://tna.trilliumtransit.com/TNAtoolAPI-Webapp/routereport.html?&areaid=41001&type=0&x=0.25&n=jer&dbindex=10&popYear=2010&geotype=-1&geoid=null&nav=stateS-countyS

**Comment by ed-g** [comment]
Thanks!

**Comment by PPaulsonOregonDOT** [comment]
@ed-g: This might shed some light on the reason that the reports are timing out. I'm not entirely sure the reports that those hyperlinks point to exist any longer. as an example of the routes report reached from the agency report, which appears to be empty.
http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/routereport.html?&agency=101&x=0.25&n=jer&dbindex=10&popYear=2010&nav=stateS-agencyS
