### ISSUE TITLE
date selection broken on many pages

### ISSUE THREAD

**Issue by ed-g** [pouyalireza/TNAST_MAVEN#68]
Date selection followed by submit fails on many pages.

It would be great to have 3 example URL's that fail here. @PPaulsonOregonDOT @srinivas13794 @BenFields724 can you post comments to this ticket with a URL that fails?

@srinivas13794 @BenFields724 you mentioned there were problems with a library. Can you give 
* a URL link to the library itself
* A file and line number (or github link works too) where you're using it in the source code.

> I was looking into the problem of date select.There seems to be a problem with
> a library that enables us to select multiple dates.Would you be free for a
> brief call in order to discuss this?

**Comment by PPaulsonOregonDOT** [comment]
http://tna.trilliumtransit.com/TNAtoolAPI-Webapp/GeoStateXreport.html?&x=0.25&l=2&n=izr&dbindex=10&areaId=41&popYear=2010&nav=stateS

http://tna.trilliumtransit.com/TNAtoolAPI-Webapp/AgenXReport.html?&agency=101&x=0.25&l=2&n=izr&dbindex=10&popYear=2010&areaid=null&type=0&username=admin&geotype=-1&geoid=null&nav=stateS-agencyS

http://tna.trilliumtransit.com/TNAtoolAPI-Webapp/GeoCountiesXreport.html?&areaid=41001&x=0.25&l=2&n=izr&dbindex=10&popYear=2010&nav=stateS-countyS

**Comment by srinivas13794** [comment]
@BenFields724 @ed-g @PPaulsonOregonDOT @ODOT-RPTD-mb We were able to find the problem and fix it.The [development version](http://tna.trilliumtransit.com:8080/?&n=--&dbindex=10) of the trillium server should now be updated with the latest changes.Please let me know if you encounter this problem again in your testing.

**Comment by ed-g** [comment]
https://github.com/pouyalireza/TNAST_MAVEN/commit/40474d3c2cca3402e99a5a2af332cd037e5dc302

**Comment by ed-g** [comment]
@PPaulsonOregonDOT can you test on your side and verify this is fixed? I tested and it seemed to work.

**Comment by ed-g** [comment]
Srinivas: this should work fine.

**Comment by ed-g** [comment]
If we find any problems with other reports, OK to email Srinivas to ask questions.
