### ISSUE TITLE
finer resolution than the census block

### ISSUE THREAD

**Issue by antrim** [pouyalireza/TNAST_MAVEN#7]
We have requested that ODOT’s GIS group replicate TNA tool “served by” and “served at level of service” functionality. This work may result in some questions related to the precise meaning of “served by” and “served at level of service”. Phil will be working with the GIS group to get them the right starting data. In addition to calculating results based on census block internal points, the GIS group will also perform the same calculations, but based on block boundaries and estimate pop served by % of block within buffer, i.e. 17% of area within buffer -> 17% of pop in block served. GIS group will report on differences in results between the two estimation practices. We have also asked the GIS group to investigate the availability of census data at a finer resolution than the census block for a possible third method of allocating population to buffers. [ODOT will drive this activity]

**Comment by PPaulsonOregonDOT** [comment]
From my first reading of the analysis done by the GIS group at the county level, for the total population calculation the TNA tool outputs are about 5% higher than the the area weighted calculation. When looking at urban areas, this rises to 10%, and in rural areas, it rises to around 20%. Most of the R squared's for the linear regression model between these two measurements were in the mid to high .9's, so there weren't huge outliers that were calculated differently.

**Comment by pouyalireza** [comment]
I am not sure what the next step with regard to this task would be @PPaulsonOregonDOT. @ed-g I think we would need more information for us to tag this task.

**Comment by PPaulsonOregonDOT** [comment]
I shared the initial results of the analysis above, we're still fixing an internal data issue and doing more analysis of the data to determine if there is a followup request we have for added TNAST functionality as a result of this analysis.

**Comment by ODOT-RPTD-mb** [comment]
May revisit this or related issues in the future, but will start fresh or re-open if needed.
