### ISSUE TITLE
update RVTD for new calendar.txt

### ISSUE THREAD

**Issue by ed-g** [pouyalireza/TNAST_MAVEN#73]

**Comment by PPaulsonOregonDOT** [comment]
This points to a bigger conversation that we need to have about what the tool looks at in terms of "up to date" data. RVTD's feed doesn't expire until 2025, but their calendar.txt end date is 9/1 on the old feed and the same file has a start date of 9/25 in the newest feed, which is the same date as it was refreshed on oregon-gtfs.com. The feed validator didn't throw an issue with this feed, which would suggest it's not out of spec, but it causes some problematic behavior in the tool.

**Comment by ODOT-RPTD-mb** [comment]
Closing this issue and folding under #4
